/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddonProduct {
  'id' : string,
  'displayOrder' : bigint,
  'name' : string,
  'description' : [] | [string],
  'codEnabled' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface AdminEmailConfig {
  'isEnabled' : boolean,
  'fromName' : string,
  'adminEmail' : string,
  'replyTo' : string,
}
export type ArtStyle = { 'FunnyExaggerated' : null } |
  { 'ProfessionalPortrait' : null } |
  { 'CuteCartoon' : null } |
  { 'CoupleIllustration' : null } |
  { 'Chibi' : null } |
  { 'SoftAesthetic' : null };
export interface AuthResult { 'message' : string, 'success' : boolean }
export interface BrowseLeadInput {
  'name' : string,
  'recipient' : [] | [string],
  'productInterest' : [] | [string],
  'phone' : string,
}
export interface Cart {
  'id' : string,
  'createdAt' : string,
  'updatedAt' : string,
  'customerId' : [] | [string],
  'sessionId' : string,
  'items' : Array<CartItem>,
}
export interface CartItem {
  'name' : string,
  'productId' : string,
  'flowType' : string,
  'quantity' : bigint,
  'image' : string,
  'price' : bigint,
  'itemImages' : Array<string>,
}
export interface CartLead {
  'id' : bigint,
  'status' : string,
  'leadType' : LeadType,
  'productIds' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'recipient' : [] | [string],
  'productName' : string,
  'email' : string,
  'assignedRep' : [] | [string],
  'productInterest' : [] | [string],
  'phone' : string,
}
export interface CartLeadInput {
  'leadType' : LeadType,
  'productIds' : Array<string>,
  'name' : string,
  'productName' : string,
  'email' : string,
  'phone' : string,
}
export interface CartResponse {
  'cart' : [] | [Cart],
  'message' : string,
  'success' : boolean,
}
export interface CheckoutLeadInput {
  'productIds' : Array<string>,
  'name' : string,
  'phone' : string,
}
export interface CommunicationLog {
  'id' : string,
  'status' : EmailStatus,
  'subject' : string,
  'messages' : Array<CommunicationMessage>,
  'templateId' : EmailTemplateId,
  'body' : string,
  'errorMessage' : [] | [string],
  'templateName' : string,
  'sentAt' : [] | [bigint],
  'orderId' : string,
  'adminSeenAt' : [] | [bigint],
  'recipientEmail' : string,
}
export interface CommunicationMessage {
  'direction' : MessageDirection,
  'body' : string,
  'isRead' : boolean,
  'author' : [] | [string],
  'timestamp' : bigint,
}
export interface ConfirmPaymentResponse { 'orderId' : OrderId }
export interface CreateOrderRequest {
  'customerName' : string,
  'photoKeys' : Array<ExternalBlob>,
  'deliveryAddress' : DeliveryAddress,
  'portraitType' : string,
  'paymentMethod' : PaymentMethod,
  'selectedAddOns' : string,
  'customerPhone' : string,
  'is3DModel' : boolean,
  'cartoonStyle' : string,
  'customerAcknowledged' : boolean,
  'specialInstructions' : [] | [string],
  'referredBy' : string,
  'address' : string,
  'notes' : string,
  'paymentMode' : PaymentMode,
  'customerId' : string,
  'addOnsAmount' : bigint,
  'pincode' : string,
  'customerEmail' : string,
  'portraitPrice' : bigint,
  'orderItems' : Array<OrderItem>,
}
export interface CreateOrderResponse {
  'orderId' : OrderId,
  'currency' : string,
  'razorpayOrder' : [] | [RazorpayOrderDetails],
  'amount' : bigint,
}
export interface Customer {
  'id' : CustomerId,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'updatedAt' : bigint,
  'phone' : string,
}
export type CustomerId = bigint;
export interface CustomerWithOrders {
  'customer' : Customer,
  'orderCount' : bigint,
}
export interface DeliveryAddress {
  'country' : string,
  'city' : string,
  'fullName' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'pincode' : string,
}
export type EmailStatus = { 'Failed' : null } |
  { 'Sent' : null } |
  { 'Pending' : null };
export interface EmailTemplate {
  'id' : EmailTemplateId,
  'subject' : string,
  'body' : string,
  'name' : string,
  'isActive' : boolean,
  'variables' : Array<string>,
  'category' : string,
}
export type EmailTemplateId = string;
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : string,
  'title' : string,
  'displayOrder' : bigint,
  'isActive' : boolean,
  'imageUrl' : string,
  'uploadedAt' : bigint,
}
export type HeroPlatform = { 'Both' : null } |
  { 'Website' : null } |
  { 'Mobile' : null };
export interface HeroVideo {
  'id' : string,
  'title' : string,
  'displayOrder' : bigint,
  'platform' : [] | [HeroPlatform],
  'isActive' : boolean,
  'isDefault' : boolean,
  'videoUrl' : string,
  'uploadedAt' : bigint,
}
export interface HeroVideoSettings {
  'muted' : boolean,
  'autoplay' : boolean,
  'loopEnabled' : boolean,
  'keepVolumeOn' : boolean,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface Lead {
  'id' : string,
  'status' : string,
  'subject' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type LeadType = { 'Browse' : null } |
  { 'CartAbandon' : null } |
  { 'Checkout' : null };
export type MessageDirection = { 'Sent' : null } |
  { 'Received' : null };
export interface MobileWebAppSettings {
  'appName' : string,
  'primaryColor' : string,
  'splashScreenUrl' : string,
  'heroVideoIds' : Array<string>,
  'secondaryColor' : string,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'notificationType' : NotificationType,
  'link' : [] | [string],
  'isRead' : boolean,
  'orderId' : [] | [string],
  'logId' : [] | [string],
  'message' : string,
  'timestamp' : bigint,
}
export type NotificationType = { 'Message' : null } |
  { 'Order' : null };
export interface Order {
  'razorpayPaymentId' : [] | [string],
  'customerName' : string,
  'photoKeys' : Array<ExternalBlob>,
  'deliveryAddress' : [] | [DeliveryAddress],
  'portraitType' : PortraitType,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : [] | [PaymentMethod],
  'selectedAddOns' : [] | [string],
  'portraitTypeText' : [] | [string],
  'customerPhone' : string,
  'orderStatus' : OrderStatus,
  'createdAt' : Timestamp,
  'is3DModel' : boolean,
  'estimatedDelivery' : Timestamp,
  'cartoonStyle' : string,
  'estimatedDeliveryText' : string,
  'isRead' : boolean,
  'customerAcknowledged' : boolean,
  'orderId' : OrderId,
  'specialInstructions' : [] | [string],
  'referredBy' : [] | [string],
  'upiRef' : [] | [string],
  'razorpayOrderId' : [] | [string],
  'totalAmount' : bigint,
  'address' : string,
  'notes' : string,
  'advancePaid' : bigint,
  'artStyle' : ArtStyle,
  'paymentMode' : PaymentMode,
  'customerId' : [] | [string],
  'addOnsAmount' : bigint,
  'finalArtworkKey' : [] | [ExternalBlob],
  'pincode' : string,
  'paymentRef' : [] | [string],
  'amount' : bigint,
  'customerEmail' : string,
  'portraitPrice' : bigint,
  'orderItems' : Array<OrderItem>,
}
export type OrderId = string;
export interface OrderItem {
  'name' : string,
  'productId' : string,
  'flowType' : string,
  'quantity' : bigint,
  'price' : bigint,
  'itemImages' : Array<string>,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Received' : null } |
  { 'Shipped' : null } |
  { 'OutForDelivery' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type PaymentMethod = { 'COD' : null } |
  { 'Razorpay' : null };
export type PaymentMode = { 'Full' : null } |
  { 'Advance' : null };
export type PaymentStatus = { 'Failed' : null } |
  { 'Paid' : null } |
  { 'AdvancePaid' : null } |
  { 'Pending' : null };
export type PortraitType = { 'Couple' : null } |
  { 'Family' : null } |
  { 'Group' : null } |
  { 'Single' : null };
export interface RazorpayOrderDetails {
  'orderId' : string,
  'currency' : string,
  'amount' : bigint,
  'keyId' : string,
}
export interface RequestOtpRequest { 'phone' : string }
export interface RequestOtpResponse { 'message' : string, 'success' : boolean }
export interface Review {
  'id' : string,
  'status' : ReviewStatus,
  'name' : string,
  'createdAt' : bigint,
  'text' : string,
  'updatedAt' : bigint,
  'imageUrl' : [] | [string],
  'rating' : bigint,
}
export type ReviewStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface SalesRep {
  'principal' : string,
  'name' : [] | [string],
  'email' : [] | [string],
  'addedAt' : bigint,
  'phone' : [] | [string],
}
export type SalesRepList = Array<SalesRep>;
export interface SendTemplateEmailRequest {
  'templateId' : EmailTemplateId,
  'orderId' : string,
  'customVariables' : Array<[string, string]>,
}
export type SendTemplateEmailResponse = { 'ok' : CommunicationLog } |
  { 'err' : string };
export interface TeamMember {
  'id' : string,
  'displayOrder' : bigint,
  'name' : string,
  'role' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'uploadedAt' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface UpdateAdminEmailConfigRequest {
  'isEnabled' : boolean,
  'fromName' : string,
  'adminEmail' : string,
  'replyTo' : string,
}
export interface UpdateCustomerRequest { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerifyOtpRequest {
  'otp' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface VerifyOtpResponse {
  'token' : [] | [string],
  'customer' : [] | [Customer],
  'message' : string,
  'success' : boolean,
}
export interface WebsiteSettings {
  'primaryColor' : string,
  'heroVideoIds' : Array<string>,
  'instagramUrl' : string,
  'siteName' : string,
  'whatsappNumber' : string,
  'logoUrl' : string,
  'contactEmail' : string,
  'secondaryColor' : string,
  'contactPhone' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCustomerReply' : ActorMethod<
    [OrderId, EmailTemplateId, string],
    SendTemplateEmailResponse
  >,
  'addCustomerReplyPublic' : ActorMethod<
    [OrderId, string, string],
    SendTemplateEmailResponse
  >,
  'addGalleryImage' : ActorMethod<[string, string], GalleryImage>,
  'addHeroVideo' : ActorMethod<[string, string, HeroPlatform], HeroVideo>,
  'addProduct' : ActorMethod<
    [string, bigint, string, string, boolean, [] | [string]],
    string
  >,
  'addReview' : ActorMethod<[string, string, bigint, [] | [string]], Review>,
  'addSalesRep' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addTeamMember' : ActorMethod<[string, string, string], TeamMember>,
  'addToCart' : ActorMethod<[string, [] | [string], CartItem], CartResponse>,
  'approveReview' : ActorMethod<[string], [] | [Review]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLeadToRep' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'clearCart' : ActorMethod<[string, [] | [string]], CartResponse>,
  'confirmRazorpayPayment' : ActorMethod<
    [string, string, string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'confirmUpiPayment' : ActorMethod<
    [string, string],
    { 'ok' : ConfirmPaymentResponse } |
      { 'err' : string }
  >,
  'createBulkOrder' : ActorMethod<[CreateOrderRequest], CreateOrderResponse>,
  'createCart' : ActorMethod<[string], CartResponse>,
  'createOrder' : ActorMethod<[CreateOrderRequest], CreateOrderResponse>,
  'deleteCartLead' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteGalleryImage' : ActorMethod<[string], boolean>,
  'deleteHeroVideo' : ActorMethod<[string], boolean>,
  'deleteLead' : ActorMethod<[string], boolean>,
  'deleteMessage' : ActorMethod<[string, bigint], undefined>,
  'deleteOrder' : ActorMethod<[OrderId], { 'ok' : null } | { 'err' : string }>,
  'deleteProduct' : ActorMethod<[string], boolean>,
  'deleteReview' : ActorMethod<[string], boolean>,
  'deleteTeamMember' : ActorMethod<[string], boolean>,
  'getActiveGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getActiveHeroVideos' : ActorMethod<[], Array<HeroVideo>>,
  'getActiveHeroVideosByPlatform' : ActorMethod<
    [HeroPlatform],
    Array<HeroVideo>
  >,
  'getActiveTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getAdminEmailConfig' : ActorMethod<[], AdminEmailConfig>,
  'getAllCustomersWithOrders' : ActorMethod<[], Array<CustomerWithOrders>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[string, [] | [string]], CartResponse>,
  'getCartLeads' : ActorMethod<[], Array<CartLead>>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getCustomerCount' : ActorMethod<[], bigint>,
  'getEmailTemplate' : ActorMethod<[EmailTemplateId], [] | [EmailTemplate]>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getHeroVideoSettings' : ActorMethod<[], HeroVideoSettings>,
  'getHeroVideos' : ActorMethod<[], Array<HeroVideo>>,
  'getMobileWebAppSettings' : ActorMethod<[], MobileWebAppSettings>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrdersByCustomer' : ActorMethod<[string], Array<Order>>,
  'getProduct' : ActorMethod<[string], [] | [AddonProduct]>,
  'getPublicCommunicationLogs' : ActorMethod<
    [OrderId],
    Array<CommunicationLog>
  >,
  'getPublicReviews' : ActorMethod<[], Array<[string, Review]>>,
  'getRazorpayCheckoutPayload' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getRazorpayKeyId' : ActorMethod<[], [] | [string]>,
  'getRazorpayPublicKeyId' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getRecentNotifications' : ActorMethod<[bigint], Array<Notification>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getUnreadMessagesCount' : ActorMethod<[], bigint>,
  'getUnreadOrdersCount' : ActorMethod<[], bigint>,
  'getWebsiteSettings' : ActorMethod<[], WebsiteSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerFounder' : ActorMethod<[], boolean>,
  'isCallerSalesRep' : ActorMethod<[], boolean>,
  'linkAnonymousOrders' : ActorMethod<[string, string, string], bigint>,
  'listAllCommunicationLogs' : ActorMethod<[], Array<CommunicationLog>>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listCommunicationLogs' : ActorMethod<[OrderId], Array<CommunicationLog>>,
  'listEmailTemplates' : ActorMethod<[], Array<EmailTemplate>>,
  'listLeads' : ActorMethod<[], Array<Lead>>,
  'listPendingReviews' : ActorMethod<[], Array<[string, Review]>>,
  'listProducts' : ActorMethod<[], Array<AddonProduct>>,
  'listReviews' : ActorMethod<[], Array<[string, Review]>>,
  'listSalesReps' : ActorMethod<[], SalesRepList>,
  'logout' : ActorMethod<[string], AuthResult>,
  'markMessageAsRead' : ActorMethod<[string, bigint], undefined>,
  'markOrderAsSeen' : ActorMethod<[string], undefined>,
  'mergeCarts' : ActorMethod<[string, string], CartResponse>,
  'moveProductDown' : ActorMethod<[string], undefined>,
  'moveProductUp' : ActorMethod<[string], undefined>,
  'rejectReview' : ActorMethod<[string], [] | [Review]>,
  'removeFromCart' : ActorMethod<[string, [] | [string], string], CartResponse>,
  'removeSalesRep' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'reorderProducts' : ActorMethod<[Array<string>], undefined>,
  'reorderTeamMembers' : ActorMethod<[Array<string>], undefined>,
  'requestOTP' : ActorMethod<[RequestOtpRequest], RequestOtpResponse>,
  'saveBrowseLead' : ActorMethod<
    [BrowseLeadInput],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'saveCartLead' : ActorMethod<
    [CartLeadInput],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'saveCheckoutLead' : ActorMethod<
    [CheckoutLeadInput],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'saveLead' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveRazorpayKeys' : ActorMethod<[string, string], boolean>,
  'seedDefaultProducts' : ActorMethod<[], bigint>,
  'sendCustomEmail' : ActorMethod<
    [OrderId, string, string],
    SendTemplateEmailResponse
  >,
  'sendPaymentReminder' : ActorMethod<[OrderId], SendTemplateEmailResponse>,
  'sendTemplateEmail' : ActorMethod<
    [SendTemplateEmailRequest],
    SendTemplateEmailResponse
  >,
  'setHeroVideoSettings' : ActorMethod<
    [boolean, boolean, boolean, boolean],
    HeroVideoSettings
  >,
  'submitReview' : ActorMethod<[string, string, bigint, [] | [string]], Review>,
  'teamListCartLeads' : ActorMethod<[], Array<CartLead>>,
  'teamListLeads' : ActorMethod<[], Array<Lead>>,
  'teamListOrders' : ActorMethod<[], Array<Order>>,
  'teamListProducts' : ActorMethod<[], Array<AddonProduct>>,
  'teamUpdateCartLeadStatus' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'teamUpdateLeadStatus' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'toggleProductCOD' : ActorMethod<[string, boolean], string>,
  'toggleTemplateActive' : ActorMethod<[EmailTemplateId, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminEmailConfig' : ActorMethod<
    [UpdateAdminEmailConfigRequest],
    undefined
  >,
  'updateCartLeadStatus' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCustomer' : ActorMethod<[string, UpdateCustomerRequest], AuthResult>,
  'updateEmailTemplate' : ActorMethod<
    [EmailTemplateId, EmailTemplate],
    undefined
  >,
  'updateGalleryImage' : ActorMethod<
    [string, string, bigint, boolean],
    [] | [GalleryImage]
  >,
  'updateHeroVideo' : ActorMethod<
    [string, boolean, boolean, bigint, HeroPlatform],
    [] | [HeroVideo]
  >,
  'updateLeadStatus' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMobileWebAppSettings' : ActorMethod<
    [MobileWebAppSettings],
    MobileWebAppSettings
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updatePaymentStatus' : ActorMethod<[OrderId, PaymentStatus], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, bigint, string, string, boolean, [] | [string]],
    boolean
  >,
  'updateProductImage' : ActorMethod<[string, string], boolean>,
  'updateQuantity' : ActorMethod<
    [string, [] | [string], string, bigint],
    CartResponse
  >,
  'updateReview' : ActorMethod<
    [string, string, string, bigint, [] | [string], [] | [ReviewStatus]],
    [] | [Review]
  >,
  'updateTeamMember' : ActorMethod<
    [string, string, string, string, bigint, boolean],
    [] | [TeamMember]
  >,
  'updateWebsiteSettings' : ActorMethod<[WebsiteSettings], WebsiteSettings>,
  'uploadFinalArtwork' : ActorMethod<[OrderId, ExternalBlob], undefined>,
  'verifyOTP' : ActorMethod<[VerifyOtpRequest], VerifyOtpResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];