/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const OrderId = IDL.Text;
export const EmailTemplateId = IDL.Text;
export const EmailStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Sent' : IDL.Null,
  'Pending' : IDL.Null,
});
export const MessageDirection = IDL.Variant({
  'Sent' : IDL.Null,
  'Received' : IDL.Null,
});
export const CommunicationMessage = IDL.Record({
  'direction' : MessageDirection,
  'body' : IDL.Text,
  'isRead' : IDL.Bool,
  'author' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const CommunicationLog = IDL.Record({
  'id' : IDL.Text,
  'status' : EmailStatus,
  'subject' : IDL.Text,
  'messages' : IDL.Vec(CommunicationMessage),
  'templateId' : EmailTemplateId,
  'body' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
  'templateName' : IDL.Text,
  'sentAt' : IDL.Opt(IDL.Int),
  'orderId' : IDL.Text,
  'adminSeenAt' : IDL.Opt(IDL.Int),
  'recipientEmail' : IDL.Text,
});
export const SendTemplateEmailResponse = IDL.Variant({
  'ok' : CommunicationLog,
  'err' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const HeroPlatform = IDL.Variant({
  'Both' : IDL.Null,
  'Website' : IDL.Null,
  'Mobile' : IDL.Null,
});
export const HeroVideo = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'platform' : IDL.Opt(HeroPlatform),
  'isActive' : IDL.Bool,
  'isDefault' : IDL.Bool,
  'videoUrl' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const ReviewStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'status' : ReviewStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'updatedAt' : IDL.Int,
  'imageUrl' : IDL.Opt(IDL.Text),
  'rating' : IDL.Nat,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const CartItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : IDL.Text,
  'flowType' : IDL.Text,
  'quantity' : IDL.Nat,
  'image' : IDL.Text,
  'price' : IDL.Nat,
  'itemImages' : IDL.Vec(IDL.Text),
});
export const Cart = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Text,
  'updatedAt' : IDL.Text,
  'customerId' : IDL.Opt(IDL.Text),
  'sessionId' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const CartResponse = IDL.Record({
  'cart' : IDL.Opt(Cart),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConfirmPaymentResponse = IDL.Record({ 'orderId' : OrderId });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DeliveryAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'pincode' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'COD' : IDL.Null,
  'Razorpay' : IDL.Null,
});
export const PaymentMode = IDL.Variant({
  'Full' : IDL.Null,
  'Advance' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : IDL.Text,
  'flowType' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'itemImages' : IDL.Vec(IDL.Text),
});
export const CreateOrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'photoKeys' : IDL.Vec(ExternalBlob),
  'deliveryAddress' : DeliveryAddress,
  'portraitType' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'selectedAddOns' : IDL.Text,
  'customerPhone' : IDL.Text,
  'is3DModel' : IDL.Bool,
  'cartoonStyle' : IDL.Text,
  'customerAcknowledged' : IDL.Bool,
  'specialInstructions' : IDL.Opt(IDL.Text),
  'referredBy' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'paymentMode' : PaymentMode,
  'customerId' : IDL.Text,
  'addOnsAmount' : IDL.Nat,
  'pincode' : IDL.Text,
  'customerEmail' : IDL.Text,
  'portraitPrice' : IDL.Nat,
  'orderItems' : IDL.Vec(OrderItem),
});
export const RazorpayOrderDetails = IDL.Record({
  'orderId' : IDL.Text,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
  'keyId' : IDL.Text,
});
export const CreateOrderResponse = IDL.Record({
  'orderId' : OrderId,
  'currency' : IDL.Text,
  'razorpayOrder' : IDL.Opt(RazorpayOrderDetails),
  'amount' : IDL.Nat,
});
export const AdminEmailConfig = IDL.Record({
  'isEnabled' : IDL.Bool,
  'fromName' : IDL.Text,
  'adminEmail' : IDL.Text,
  'replyTo' : IDL.Text,
});
export const CustomerId = IDL.Nat;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'phone' : IDL.Text,
});
export const CustomerWithOrders = IDL.Record({
  'customer' : Customer,
  'orderCount' : IDL.Nat,
});
export const LeadType = IDL.Variant({
  'Browse' : IDL.Null,
  'CartAbandon' : IDL.Null,
  'Checkout' : IDL.Null,
});
export const CartLead = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'leadType' : LeadType,
  'productIds' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'recipient' : IDL.Opt(IDL.Text),
  'productName' : IDL.Text,
  'email' : IDL.Text,
  'assignedRep' : IDL.Opt(IDL.Text),
  'productInterest' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const EmailTemplate = IDL.Record({
  'id' : EmailTemplateId,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'variables' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const HeroVideoSettings = IDL.Record({
  'muted' : IDL.Bool,
  'autoplay' : IDL.Bool,
  'loopEnabled' : IDL.Bool,
  'keepVolumeOn' : IDL.Bool,
});
export const MobileWebAppSettings = IDL.Record({
  'appName' : IDL.Text,
  'primaryColor' : IDL.Text,
  'splashScreenUrl' : IDL.Text,
  'heroVideoIds' : IDL.Vec(IDL.Text),
  'secondaryColor' : IDL.Text,
});
export const PortraitType = IDL.Variant({
  'Couple' : IDL.Null,
  'Family' : IDL.Null,
  'Group' : IDL.Null,
  'Single' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Paid' : IDL.Null,
  'AdvancePaid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Received' : IDL.Null,
  'Shipped' : IDL.Null,
  'OutForDelivery' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ArtStyle = IDL.Variant({
  'FunnyExaggerated' : IDL.Null,
  'ProfessionalPortrait' : IDL.Null,
  'CuteCartoon' : IDL.Null,
  'CoupleIllustration' : IDL.Null,
  'Chibi' : IDL.Null,
  'SoftAesthetic' : IDL.Null,
});
export const Order = IDL.Record({
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'customerName' : IDL.Text,
  'photoKeys' : IDL.Vec(ExternalBlob),
  'deliveryAddress' : IDL.Opt(DeliveryAddress),
  'portraitType' : PortraitType,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'selectedAddOns' : IDL.Opt(IDL.Text),
  'portraitTypeText' : IDL.Opt(IDL.Text),
  'customerPhone' : IDL.Text,
  'orderStatus' : OrderStatus,
  'createdAt' : Timestamp,
  'is3DModel' : IDL.Bool,
  'estimatedDelivery' : Timestamp,
  'cartoonStyle' : IDL.Text,
  'estimatedDeliveryText' : IDL.Text,
  'isRead' : IDL.Bool,
  'customerAcknowledged' : IDL.Bool,
  'orderId' : OrderId,
  'specialInstructions' : IDL.Opt(IDL.Text),
  'referredBy' : IDL.Opt(IDL.Text),
  'upiRef' : IDL.Opt(IDL.Text),
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'advancePaid' : IDL.Nat,
  'artStyle' : ArtStyle,
  'paymentMode' : PaymentMode,
  'customerId' : IDL.Opt(IDL.Text),
  'addOnsAmount' : IDL.Nat,
  'finalArtworkKey' : IDL.Opt(ExternalBlob),
  'pincode' : IDL.Text,
  'paymentRef' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'customerEmail' : IDL.Text,
  'portraitPrice' : IDL.Nat,
  'orderItems' : IDL.Vec(OrderItem),
});
export const AddonProduct = IDL.Record({
  'id' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'codEnabled' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'Message' : IDL.Null,
  'Order' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'notificationType' : NotificationType,
  'link' : IDL.Opt(IDL.Text),
  'isRead' : IDL.Bool,
  'orderId' : IDL.Opt(IDL.Text),
  'logId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const WebsiteSettings = IDL.Record({
  'primaryColor' : IDL.Text,
  'heroVideoIds' : IDL.Vec(IDL.Text),
  'instagramUrl' : IDL.Text,
  'siteName' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'logoUrl' : IDL.Text,
  'contactEmail' : IDL.Text,
  'secondaryColor' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const SalesRep = IDL.Record({
  'principal' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'addedAt' : IDL.Int,
  'phone' : IDL.Opt(IDL.Text),
});
export const SalesRepList = IDL.Vec(SalesRep);
export const AuthResult = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const RequestOtpRequest = IDL.Record({ 'phone' : IDL.Text });
export const RequestOtpResponse = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const BrowseLeadInput = IDL.Record({
  'name' : IDL.Text,
  'recipient' : IDL.Opt(IDL.Text),
  'productInterest' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const CartLeadInput = IDL.Record({
  'leadType' : LeadType,
  'productIds' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'productName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CheckoutLeadInput = IDL.Record({
  'productIds' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const SendTemplateEmailRequest = IDL.Record({
  'templateId' : EmailTemplateId,
  'orderId' : IDL.Text,
  'customVariables' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const UpdateAdminEmailConfigRequest = IDL.Record({
  'isEnabled' : IDL.Bool,
  'fromName' : IDL.Text,
  'adminEmail' : IDL.Text,
  'replyTo' : IDL.Text,
});
export const UpdateCustomerRequest = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const VerifyOtpRequest = IDL.Record({
  'otp' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const VerifyOtpResponse = IDL.Record({
  'token' : IDL.Opt(IDL.Text),
  'customer' : IDL.Opt(Customer),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCustomerReply' : IDL.Func(
      [OrderId, EmailTemplateId, IDL.Text],
      [SendTemplateEmailResponse],
      [],
    ),
  'addCustomerReplyPublic' : IDL.Func(
      [OrderId, IDL.Text, IDL.Text],
      [SendTemplateEmailResponse],
      [],
    ),
  'addGalleryImage' : IDL.Func([IDL.Text, IDL.Text], [GalleryImage], []),
  'addHeroVideo' : IDL.Func(
      [IDL.Text, IDL.Text, HeroPlatform],
      [HeroVideo],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [Review],
      [],
    ),
  'addSalesRep' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addTeamMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [TeamMember], []),
  'addToCart' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), CartItem],
      [CartResponse],
      [],
    ),
  'approveReview' : IDL.Func([IDL.Text], [IDL.Opt(Review)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLeadToRep' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'clearCart' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [CartResponse], []),
  'confirmRazorpayPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'confirmUpiPayment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ConfirmPaymentResponse, 'err' : IDL.Text })],
      [],
    ),
  'createBulkOrder' : IDL.Func([CreateOrderRequest], [CreateOrderResponse], []),
  'createCart' : IDL.Func([IDL.Text], [CartResponse], []),
  'createOrder' : IDL.Func([CreateOrderRequest], [CreateOrderResponse], []),
  'deleteCartLead' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteGalleryImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteHeroVideo' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteLead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteMessage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteOrder' : IDL.Func(
      [OrderId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteReview' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getActiveGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getActiveHeroVideos' : IDL.Func([], [IDL.Vec(HeroVideo)], ['query']),
  'getActiveHeroVideosByPlatform' : IDL.Func(
      [HeroPlatform],
      [IDL.Vec(HeroVideo)],
      ['query'],
    ),
  'getActiveTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getAdminEmailConfig' : IDL.Func([], [AdminEmailConfig], ['query']),
  'getAllCustomersWithOrders' : IDL.Func(
      [],
      [IDL.Vec(CustomerWithOrders)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [CartResponse], []),
  'getCartLeads' : IDL.Func([], [IDL.Vec(CartLead)], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getCustomerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getEmailTemplate' : IDL.Func(
      [EmailTemplateId],
      [IDL.Opt(EmailTemplate)],
      ['query'],
    ),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getHeroVideoSettings' : IDL.Func([], [HeroVideoSettings], ['query']),
  'getHeroVideos' : IDL.Func([], [IDL.Vec(HeroVideo)], ['query']),
  'getMobileWebAppSettings' : IDL.Func([], [MobileWebAppSettings], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(AddonProduct)], ['query']),
  'getPublicCommunicationLogs' : IDL.Func(
      [OrderId],
      [IDL.Vec(CommunicationLog)],
      ['query'],
    ),
  'getPublicReviews' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Review))],
      ['query'],
    ),
  'getRazorpayCheckoutPayload' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      ['query'],
    ),
  'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getRazorpayPublicKeyId' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      ['query'],
    ),
  'getRecentNotifications' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUnreadMessagesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadOrdersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getWebsiteSettings' : IDL.Func([], [WebsiteSettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerFounder' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerSalesRep' : IDL.Func([], [IDL.Bool], ['query']),
  'linkAnonymousOrders' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'listAllCommunicationLogs' : IDL.Func(
      [],
      [IDL.Vec(CommunicationLog)],
      ['query'],
    ),
  'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listCommunicationLogs' : IDL.Func(
      [OrderId],
      [IDL.Vec(CommunicationLog)],
      ['query'],
    ),
  'listEmailTemplates' : IDL.Func([], [IDL.Vec(EmailTemplate)], ['query']),
  'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'listPendingReviews' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Review))],
      ['query'],
    ),
  'listProducts' : IDL.Func([], [IDL.Vec(AddonProduct)], ['query']),
  'listReviews' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Review))],
      ['query'],
    ),
  'listSalesReps' : IDL.Func([], [SalesRepList], ['query']),
  'logout' : IDL.Func([IDL.Text], [AuthResult], []),
  'markMessageAsRead' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'markOrderAsSeen' : IDL.Func([IDL.Text], [], []),
  'mergeCarts' : IDL.Func([IDL.Text, IDL.Text], [CartResponse], []),
  'moveProductDown' : IDL.Func([IDL.Text], [], []),
  'moveProductUp' : IDL.Func([IDL.Text], [], []),
  'rejectReview' : IDL.Func([IDL.Text], [IDL.Opt(Review)], []),
  'removeFromCart' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [CartResponse],
      [],
    ),
  'removeSalesRep' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reorderProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'reorderTeamMembers' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'requestOTP' : IDL.Func([RequestOtpRequest], [RequestOtpResponse], []),
  'saveBrowseLead' : IDL.Func(
      [BrowseLeadInput],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'saveCartLead' : IDL.Func(
      [CartLeadInput],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'saveCheckoutLead' : IDL.Func(
      [CheckoutLeadInput],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'saveLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveRazorpayKeys' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'seedDefaultProducts' : IDL.Func([], [IDL.Nat], []),
  'sendCustomEmail' : IDL.Func(
      [OrderId, IDL.Text, IDL.Text],
      [SendTemplateEmailResponse],
      [],
    ),
  'sendPaymentReminder' : IDL.Func([OrderId], [SendTemplateEmailResponse], []),
  'sendTemplateEmail' : IDL.Func(
      [SendTemplateEmailRequest],
      [SendTemplateEmailResponse],
      [],
    ),
  'setHeroVideoSettings' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [HeroVideoSettings],
      [],
    ),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [Review],
      [],
    ),
  'teamListCartLeads' : IDL.Func([], [IDL.Vec(CartLead)], ['query']),
  'teamListLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'teamListOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'teamListProducts' : IDL.Func([], [IDL.Vec(AddonProduct)], ['query']),
  'teamUpdateCartLeadStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'teamUpdateLeadStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'toggleProductCOD' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
  'toggleTemplateActive' : IDL.Func([EmailTemplateId, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminEmailConfig' : IDL.Func([UpdateAdminEmailConfigRequest], [], []),
  'updateCartLeadStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [IDL.Text, UpdateCustomerRequest],
      [AuthResult],
      [],
    ),
  'updateEmailTemplate' : IDL.Func([EmailTemplateId, EmailTemplate], [], []),
  'updateGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Opt(GalleryImage)],
      [],
    ),
  'updateHeroVideo' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Nat, HeroPlatform],
      [IDL.Opt(HeroVideo)],
      [],
    ),
  'updateLeadStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateMobileWebAppSettings' : IDL.Func(
      [MobileWebAppSettings],
      [MobileWebAppSettings],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updatePaymentStatus' : IDL.Func([OrderId, PaymentStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
  'updateProductImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateQuantity' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
      [CartResponse],
      [],
    ),
  'updateReview' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(ReviewStatus),
      ],
      [IDL.Opt(Review)],
      [],
    ),
  'updateTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Opt(TeamMember)],
      [],
    ),
  'updateWebsiteSettings' : IDL.Func([WebsiteSettings], [WebsiteSettings], []),
  'uploadFinalArtwork' : IDL.Func([OrderId, ExternalBlob], [], []),
  'verifyOTP' : IDL.Func([VerifyOtpRequest], [VerifyOtpResponse], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const OrderId = IDL.Text;
  const EmailTemplateId = IDL.Text;
  const EmailStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Sent' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const MessageDirection = IDL.Variant({
    'Sent' : IDL.Null,
    'Received' : IDL.Null,
  });
  const CommunicationMessage = IDL.Record({
    'direction' : MessageDirection,
    'body' : IDL.Text,
    'isRead' : IDL.Bool,
    'author' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const CommunicationLog = IDL.Record({
    'id' : IDL.Text,
    'status' : EmailStatus,
    'subject' : IDL.Text,
    'messages' : IDL.Vec(CommunicationMessage),
    'templateId' : EmailTemplateId,
    'body' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
    'templateName' : IDL.Text,
    'sentAt' : IDL.Opt(IDL.Int),
    'orderId' : IDL.Text,
    'adminSeenAt' : IDL.Opt(IDL.Int),
    'recipientEmail' : IDL.Text,
  });
  const SendTemplateEmailResponse = IDL.Variant({
    'ok' : CommunicationLog,
    'err' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const HeroPlatform = IDL.Variant({
    'Both' : IDL.Null,
    'Website' : IDL.Null,
    'Mobile' : IDL.Null,
  });
  const HeroVideo = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'platform' : IDL.Opt(HeroPlatform),
    'isActive' : IDL.Bool,
    'isDefault' : IDL.Bool,
    'videoUrl' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const ReviewStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'status' : ReviewStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'updatedAt' : IDL.Int,
    'imageUrl' : IDL.Opt(IDL.Text),
    'rating' : IDL.Nat,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const CartItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : IDL.Text,
    'flowType' : IDL.Text,
    'quantity' : IDL.Nat,
    'image' : IDL.Text,
    'price' : IDL.Nat,
    'itemImages' : IDL.Vec(IDL.Text),
  });
  const Cart = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Text,
    'updatedAt' : IDL.Text,
    'customerId' : IDL.Opt(IDL.Text),
    'sessionId' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const CartResponse = IDL.Record({
    'cart' : IDL.Opt(Cart),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConfirmPaymentResponse = IDL.Record({ 'orderId' : OrderId });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DeliveryAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'COD' : IDL.Null,
    'Razorpay' : IDL.Null,
  });
  const PaymentMode = IDL.Variant({ 'Full' : IDL.Null, 'Advance' : IDL.Null });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : IDL.Text,
    'flowType' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'itemImages' : IDL.Vec(IDL.Text),
  });
  const CreateOrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'photoKeys' : IDL.Vec(ExternalBlob),
    'deliveryAddress' : DeliveryAddress,
    'portraitType' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'selectedAddOns' : IDL.Text,
    'customerPhone' : IDL.Text,
    'is3DModel' : IDL.Bool,
    'cartoonStyle' : IDL.Text,
    'customerAcknowledged' : IDL.Bool,
    'specialInstructions' : IDL.Opt(IDL.Text),
    'referredBy' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'paymentMode' : PaymentMode,
    'customerId' : IDL.Text,
    'addOnsAmount' : IDL.Nat,
    'pincode' : IDL.Text,
    'customerEmail' : IDL.Text,
    'portraitPrice' : IDL.Nat,
    'orderItems' : IDL.Vec(OrderItem),
  });
  const RazorpayOrderDetails = IDL.Record({
    'orderId' : IDL.Text,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
    'keyId' : IDL.Text,
  });
  const CreateOrderResponse = IDL.Record({
    'orderId' : OrderId,
    'currency' : IDL.Text,
    'razorpayOrder' : IDL.Opt(RazorpayOrderDetails),
    'amount' : IDL.Nat,
  });
  const AdminEmailConfig = IDL.Record({
    'isEnabled' : IDL.Bool,
    'fromName' : IDL.Text,
    'adminEmail' : IDL.Text,
    'replyTo' : IDL.Text,
  });
  const CustomerId = IDL.Nat;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'phone' : IDL.Text,
  });
  const CustomerWithOrders = IDL.Record({
    'customer' : Customer,
    'orderCount' : IDL.Nat,
  });
  const LeadType = IDL.Variant({
    'Browse' : IDL.Null,
    'CartAbandon' : IDL.Null,
    'Checkout' : IDL.Null,
  });
  const CartLead = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'leadType' : LeadType,
    'productIds' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'recipient' : IDL.Opt(IDL.Text),
    'productName' : IDL.Text,
    'email' : IDL.Text,
    'assignedRep' : IDL.Opt(IDL.Text),
    'productInterest' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const EmailTemplate = IDL.Record({
    'id' : EmailTemplateId,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'variables' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const HeroVideoSettings = IDL.Record({
    'muted' : IDL.Bool,
    'autoplay' : IDL.Bool,
    'loopEnabled' : IDL.Bool,
    'keepVolumeOn' : IDL.Bool,
  });
  const MobileWebAppSettings = IDL.Record({
    'appName' : IDL.Text,
    'primaryColor' : IDL.Text,
    'splashScreenUrl' : IDL.Text,
    'heroVideoIds' : IDL.Vec(IDL.Text),
    'secondaryColor' : IDL.Text,
  });
  const PortraitType = IDL.Variant({
    'Couple' : IDL.Null,
    'Family' : IDL.Null,
    'Group' : IDL.Null,
    'Single' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Paid' : IDL.Null,
    'AdvancePaid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Received' : IDL.Null,
    'Shipped' : IDL.Null,
    'OutForDelivery' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ArtStyle = IDL.Variant({
    'FunnyExaggerated' : IDL.Null,
    'ProfessionalPortrait' : IDL.Null,
    'CuteCartoon' : IDL.Null,
    'CoupleIllustration' : IDL.Null,
    'Chibi' : IDL.Null,
    'SoftAesthetic' : IDL.Null,
  });
  const Order = IDL.Record({
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'customerName' : IDL.Text,
    'photoKeys' : IDL.Vec(ExternalBlob),
    'deliveryAddress' : IDL.Opt(DeliveryAddress),
    'portraitType' : PortraitType,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'selectedAddOns' : IDL.Opt(IDL.Text),
    'portraitTypeText' : IDL.Opt(IDL.Text),
    'customerPhone' : IDL.Text,
    'orderStatus' : OrderStatus,
    'createdAt' : Timestamp,
    'is3DModel' : IDL.Bool,
    'estimatedDelivery' : Timestamp,
    'cartoonStyle' : IDL.Text,
    'estimatedDeliveryText' : IDL.Text,
    'isRead' : IDL.Bool,
    'customerAcknowledged' : IDL.Bool,
    'orderId' : OrderId,
    'specialInstructions' : IDL.Opt(IDL.Text),
    'referredBy' : IDL.Opt(IDL.Text),
    'upiRef' : IDL.Opt(IDL.Text),
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'advancePaid' : IDL.Nat,
    'artStyle' : ArtStyle,
    'paymentMode' : PaymentMode,
    'customerId' : IDL.Opt(IDL.Text),
    'addOnsAmount' : IDL.Nat,
    'finalArtworkKey' : IDL.Opt(ExternalBlob),
    'pincode' : IDL.Text,
    'paymentRef' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'customerEmail' : IDL.Text,
    'portraitPrice' : IDL.Nat,
    'orderItems' : IDL.Vec(OrderItem),
  });
  const AddonProduct = IDL.Record({
    'id' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'codEnabled' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'Message' : IDL.Null,
    'Order' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'notificationType' : NotificationType,
    'link' : IDL.Opt(IDL.Text),
    'isRead' : IDL.Bool,
    'orderId' : IDL.Opt(IDL.Text),
    'logId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const WebsiteSettings = IDL.Record({
    'primaryColor' : IDL.Text,
    'heroVideoIds' : IDL.Vec(IDL.Text),
    'instagramUrl' : IDL.Text,
    'siteName' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'logoUrl' : IDL.Text,
    'contactEmail' : IDL.Text,
    'secondaryColor' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SalesRep = IDL.Record({
    'principal' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'addedAt' : IDL.Int,
    'phone' : IDL.Opt(IDL.Text),
  });
  const SalesRepList = IDL.Vec(SalesRep);
  const AuthResult = IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool });
  const RequestOtpRequest = IDL.Record({ 'phone' : IDL.Text });
  const RequestOtpResponse = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const BrowseLeadInput = IDL.Record({
    'name' : IDL.Text,
    'recipient' : IDL.Opt(IDL.Text),
    'productInterest' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const CartLeadInput = IDL.Record({
    'leadType' : LeadType,
    'productIds' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'productName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CheckoutLeadInput = IDL.Record({
    'productIds' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SendTemplateEmailRequest = IDL.Record({
    'templateId' : EmailTemplateId,
    'orderId' : IDL.Text,
    'customVariables' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const UpdateAdminEmailConfigRequest = IDL.Record({
    'isEnabled' : IDL.Bool,
    'fromName' : IDL.Text,
    'adminEmail' : IDL.Text,
    'replyTo' : IDL.Text,
  });
  const UpdateCustomerRequest = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VerifyOtpRequest = IDL.Record({
    'otp' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VerifyOtpResponse = IDL.Record({
    'token' : IDL.Opt(IDL.Text),
    'customer' : IDL.Opt(Customer),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCustomerReply' : IDL.Func(
        [OrderId, EmailTemplateId, IDL.Text],
        [SendTemplateEmailResponse],
        [],
      ),
    'addCustomerReplyPublic' : IDL.Func(
        [OrderId, IDL.Text, IDL.Text],
        [SendTemplateEmailResponse],
        [],
      ),
    'addGalleryImage' : IDL.Func([IDL.Text, IDL.Text], [GalleryImage], []),
    'addHeroVideo' : IDL.Func(
        [IDL.Text, IDL.Text, HeroPlatform],
        [HeroVideo],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [Review],
        [],
      ),
    'addSalesRep' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [TeamMember],
        [],
      ),
    'addToCart' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), CartItem],
        [CartResponse],
        [],
      ),
    'approveReview' : IDL.Func([IDL.Text], [IDL.Opt(Review)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLeadToRep' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'clearCart' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [CartResponse], []),
    'confirmRazorpayPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'confirmUpiPayment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ConfirmPaymentResponse, 'err' : IDL.Text })],
        [],
      ),
    'createBulkOrder' : IDL.Func(
        [CreateOrderRequest],
        [CreateOrderResponse],
        [],
      ),
    'createCart' : IDL.Func([IDL.Text], [CartResponse], []),
    'createOrder' : IDL.Func([CreateOrderRequest], [CreateOrderResponse], []),
    'deleteCartLead' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteGalleryImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteHeroVideo' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteLead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteMessage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteOrder' : IDL.Func(
        [OrderId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteReview' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getActiveGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getActiveHeroVideos' : IDL.Func([], [IDL.Vec(HeroVideo)], ['query']),
    'getActiveHeroVideosByPlatform' : IDL.Func(
        [HeroPlatform],
        [IDL.Vec(HeroVideo)],
        ['query'],
      ),
    'getActiveTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getAdminEmailConfig' : IDL.Func([], [AdminEmailConfig], ['query']),
    'getAllCustomersWithOrders' : IDL.Func(
        [],
        [IDL.Vec(CustomerWithOrders)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [CartResponse], []),
    'getCartLeads' : IDL.Func([], [IDL.Vec(CartLead)], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getCustomerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getEmailTemplate' : IDL.Func(
        [EmailTemplateId],
        [IDL.Opt(EmailTemplate)],
        ['query'],
      ),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getHeroVideoSettings' : IDL.Func([], [HeroVideoSettings], ['query']),
    'getHeroVideos' : IDL.Func([], [IDL.Vec(HeroVideo)], ['query']),
    'getMobileWebAppSettings' : IDL.Func([], [MobileWebAppSettings], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(AddonProduct)], ['query']),
    'getPublicCommunicationLogs' : IDL.Func(
        [OrderId],
        [IDL.Vec(CommunicationLog)],
        ['query'],
      ),
    'getPublicReviews' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Review))],
        ['query'],
      ),
    'getRazorpayCheckoutPayload' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        ['query'],
      ),
    'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getRazorpayPublicKeyId' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        ['query'],
      ),
    'getRecentNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUnreadMessagesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadOrdersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getWebsiteSettings' : IDL.Func([], [WebsiteSettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerFounder' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerSalesRep' : IDL.Func([], [IDL.Bool], ['query']),
    'linkAnonymousOrders' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'listAllCommunicationLogs' : IDL.Func(
        [],
        [IDL.Vec(CommunicationLog)],
        ['query'],
      ),
    'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listCommunicationLogs' : IDL.Func(
        [OrderId],
        [IDL.Vec(CommunicationLog)],
        ['query'],
      ),
    'listEmailTemplates' : IDL.Func([], [IDL.Vec(EmailTemplate)], ['query']),
    'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'listPendingReviews' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Review))],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(AddonProduct)], ['query']),
    'listReviews' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Review))],
        ['query'],
      ),
    'listSalesReps' : IDL.Func([], [SalesRepList], ['query']),
    'logout' : IDL.Func([IDL.Text], [AuthResult], []),
    'markMessageAsRead' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'markOrderAsSeen' : IDL.Func([IDL.Text], [], []),
    'mergeCarts' : IDL.Func([IDL.Text, IDL.Text], [CartResponse], []),
    'moveProductDown' : IDL.Func([IDL.Text], [], []),
    'moveProductUp' : IDL.Func([IDL.Text], [], []),
    'rejectReview' : IDL.Func([IDL.Text], [IDL.Opt(Review)], []),
    'removeFromCart' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [CartResponse],
        [],
      ),
    'removeSalesRep' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reorderProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'reorderTeamMembers' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'requestOTP' : IDL.Func([RequestOtpRequest], [RequestOtpResponse], []),
    'saveBrowseLead' : IDL.Func(
        [BrowseLeadInput],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'saveCartLead' : IDL.Func(
        [CartLeadInput],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'saveCheckoutLead' : IDL.Func(
        [CheckoutLeadInput],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'saveLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveRazorpayKeys' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'seedDefaultProducts' : IDL.Func([], [IDL.Nat], []),
    'sendCustomEmail' : IDL.Func(
        [OrderId, IDL.Text, IDL.Text],
        [SendTemplateEmailResponse],
        [],
      ),
    'sendPaymentReminder' : IDL.Func(
        [OrderId],
        [SendTemplateEmailResponse],
        [],
      ),
    'sendTemplateEmail' : IDL.Func(
        [SendTemplateEmailRequest],
        [SendTemplateEmailResponse],
        [],
      ),
    'setHeroVideoSettings' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [HeroVideoSettings],
        [],
      ),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [Review],
        [],
      ),
    'teamListCartLeads' : IDL.Func([], [IDL.Vec(CartLead)], ['query']),
    'teamListLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'teamListOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'teamListProducts' : IDL.Func([], [IDL.Vec(AddonProduct)], ['query']),
    'teamUpdateCartLeadStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'teamUpdateLeadStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'toggleProductCOD' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
    'toggleTemplateActive' : IDL.Func([EmailTemplateId, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminEmailConfig' : IDL.Func(
        [UpdateAdminEmailConfigRequest],
        [],
        [],
      ),
    'updateCartLeadStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [IDL.Text, UpdateCustomerRequest],
        [AuthResult],
        [],
      ),
    'updateEmailTemplate' : IDL.Func([EmailTemplateId, EmailTemplate], [], []),
    'updateGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Opt(GalleryImage)],
        [],
      ),
    'updateHeroVideo' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Nat, HeroPlatform],
        [IDL.Opt(HeroVideo)],
        [],
      ),
    'updateLeadStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateMobileWebAppSettings' : IDL.Func(
        [MobileWebAppSettings],
        [MobileWebAppSettings],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updatePaymentStatus' : IDL.Func([OrderId, PaymentStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'updateProductImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateQuantity' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
        [CartResponse],
        [],
      ),
    'updateReview' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(ReviewStatus),
        ],
        [IDL.Opt(Review)],
        [],
      ),
    'updateTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Opt(TeamMember)],
        [],
      ),
    'updateWebsiteSettings' : IDL.Func(
        [WebsiteSettings],
        [WebsiteSettings],
        [],
      ),
    'uploadFinalArtwork' : IDL.Func([OrderId, ExternalBlob], [], []),
    'verifyOTP' : IDL.Func([VerifyOtpRequest], [VerifyOtpResponse], []),
  });
};

export const init = ({ IDL }) => { return []; };